#pragma once

enum class locale_string_t {
    BUTTON_FILE,
    BUTTON_OPEN,
    BUTTON_SAVE,
    BUTTON_TOOLS,
    BUTTON_BEGIN_RECORD,
    BUTTON_END_RECORD,
    BUTTON_MAKE_AXES,
    BUTTON_CHOOSE_RECORD_INFORMATION,
    BUTTON_CANCEL,
    BUTTON_CLOSE,
    BUTTON_OK,

    TITLE_AXES,
    TITLE_CHOOSE_RECORD_INFORMATION,
    TITLE_CONTROLLER,
    TITLE_OUTPUT,

    CHECKBOX_X_COORDINATE,
    CHECKBOX_Y_COORDINATE,
    CHECKBOX_TIME,
    CHECKBOX_FRAME_ID,

    INPUT_DISTANCE,
    INPUT_COMMAND,

    COMMAND_LOAD_FILE,
    COMMAND_GOTO_VIDEO_FRAME,
    COMMAND_GOTO_VIDEO_TIME,
    COMMAND_BEGIN_RECORD,
    COMMAND_ADD_RECORD_POINT,
    COMMAND_END_RECORD,
    COMMAND_MAKE_AXES,

    TEXT_FAILED_TO_LOAD_FROM,
    TEXT_LOADED_FROM,
    TEXT_RESOLUTION,
    TEXT_FRAME_COUNT,
    TEXT_LENGTH,
    TEXT_FPS,
    TEXT_BEGAN_RECORDING,
    TEXT_FINISHED_RECORDING,
    TEXT_FRAME,

    INVALID
};

enum class language_t {ENGLISH, FRENCH, INVALID};

void init_languages();
void choose_language(language_t language);
const char *get_locale_string(locale_string_t s);
